spring.datasource.url=jdbc:postgresql://localhost:5432/grooming_booking
spring.datasource.username=postgres
spring.datasource.password=postgres
starttls.enable=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kachan.nelli31@gmail.com
spring.mail.password=tshqoqatvnnjuszf

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true